"""
src/text_parser.py
Parses a single tei/texts/mrav-*.xml into a TextData object
with pre-rendered body HTML and structured apparatus entries.

IIIF facs integration:
  Loads tei/n35_facs_map.json (generated by src/fetch_iiif_map.py --offset 2).
  For each <pb n="..." wit="#N35">, looks up the IIIF service URL and sp number
  and emits data-facs / data-sp / data-folio attributes on the .folio-milestone span.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from pathlib     import Path
from typing      import List, Optional
import json
import xml.etree.ElementTree as ET
import html as html_lib

NS = {"tei": "http://www.tei-c.org/ns/1.0"}
_TEI = "http://www.tei-c.org/ns/1.0"
_XML = "http://www.w3.org/XML/1998/namespace"

def _attr(el, attrib: str, default: str = "") -> str:
    return el.get(attrib, default)

def _xml_id_attr(el) -> str:
    return el.get("{http://www.w3.org/XML/1998/namespace}id", "")


# ── Apparatus data classes ─────────────────────────────

@dataclass
class RdgData:
    text:       str
    witness:    str    # e.g. "N50"
    type_raw:   str    # e.g. "orthographic"
    type_class: str    # css class key
    type_label: str    # display label

@dataclass
class AppEntry:
    n:         int
    par_id:    str    # paragraph xml:id
    par_n:     str    # paragraph display number
    lemma:     str
    type:      str    # dominant type (for filter)
    readings:  List[RdgData] = field(default_factory=list)


# ── Full text data ─────────────────────────────────────

@dataclass
class TextData:
    # metadata (copied from TextMeta)
    xml_id:        str
    label_ka:      str
    ms_heading:    str
    author_name_ka:str
    author_name_la:str
    feast_label_ka:str
    feast_label_la:str
    locus_n35:     str
    locus_n50:     str
    cpg:           str

    # rendered content
    body_html:     str
    apparatus:     List[AppEntry] = field(default_factory=list)
    app_count:     int = 0

    # IIIF: first folio facs URL for viewer initialisation
    first_facs:    str = ""
    first_folio:   str = ""
    first_sp:      int = 0

    # navigation (filled by build.py)
    prev: Optional[object] = field(default=None, repr=False)
    next: Optional[object] = field(default=None, repr=False)

    @property
    def label_short(self) -> str:
        words = self.label_ka.split()
        return " ".join(words[:4]) + ("…" if len(words) > 4 else "")


# ── IIIF facs map loader ───────────────────────────────

def _load_facs_map(xml_path: Path) -> dict:
    """
    Try to load tei/n35_facs_map.json relative to the project root.
    xml_path is tei/texts/mrav-*.xml → project root is xml_path.parent.parent.parent.
    Falls back to the @facs attribute on <pb> if the map is unavailable.
    Returns dict keyed by folio label, e.g. {"1r": {"facs": "...", "sp": 3}, ...}
    """
    # tei/texts/file.xml → tei/ → project root
    project_root = xml_path.resolve().parent.parent.parent
    map_path = project_root / "tei" / "n35_facs_map.json"
    if not map_path.exists():
        # also try sibling of tei/texts/
        map_path2 = xml_path.resolve().parent.parent / "n35_facs_map.json"
        if map_path2.exists():
            map_path = map_path2
        else:
            return {}
    try:
        with open(map_path, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


# ── Parser ─────────────────────────────────────────────

class TextParser:

    RDG_TYPES = {
        "orthographic": ("rdg-orth", "მართლ."),
        "grammatical":  ("rdg-gram", "გრამ."),
        "lexical":      ("rdg-lex",  "ლექ."),
        "omission":     ("rdg-om",   "გამოტ."),
        "addition":     ("rdg-add",  "დამ."),
    }

    def __init__(self, xml_path: Path, meta):
        self.path = xml_path
        self.meta = meta  # TextMeta from catalog
        self._app_counter = 0
        self._apparatus: List[AppEntry] = []
        self._facs_map: dict = _load_facs_map(xml_path)
        self._first_facs = ""
        self._first_folio = ""
        self._first_sp = 0

    def parse(self) -> TextData:
        tree = ET.parse(self.path)
        root = tree.getroot()

        body_el = root.find(".//tei:body", NS)
        body_html = self._render_body(body_el) if body_el is not None else ""

        return TextData(
            xml_id        = self.meta.xml_id,
            label_ka      = self.meta.label_ka,
            ms_heading    = self.meta.ms_heading,
            author_name_ka= self.meta.author_name_ka,
            author_name_la= self.meta.author_name_la,
            feast_label_ka= self.meta.feast_label,
            feast_label_la= self.meta.feast_label_la,
            locus_n35     = self.meta.locus_n35,
            locus_n50     = self.meta.locus_n50,
            cpg           = self.meta.cpg,
            body_html     = body_html,
            apparatus     = self._apparatus,
            app_count     = len(self._apparatus),
            first_facs    = self._first_facs,
            first_folio   = self._first_folio,
            first_sp      = self._first_sp,
        )

    # ── Body rendering ─────────────────────────────────

    def _render_body(self, body_el: ET.Element) -> str:
        chunks = []
        for div in body_el.findall(".//tei:div[@type='text']", NS):
            for head_el in div.findall("tei:head", NS):
                chunks.append(self._render_head(head_el))
            for p_el in div.findall("tei:p", NS):
                chunks.append(self._render_paragraph(p_el))
            # ── CHANGE 1: render <trailer> if present ──────────────────────
            trailer_el = div.find("tei:trailer", NS)
            if trailer_el is not None:
                chunks.append(self._render_trailer(trailer_el))
        return "\n".join(chunks)

    def _render_head(self, head_el: ET.Element) -> str:
        head_type = head_el.get("type", "")
        # lb_as_br=True: <lb> elements inside rubric/dateline become <br>
        inner = "".join(self._render_children(head_el, "", "", lb_as_br=True))
        if head_type == "rubric":
            return f'<div class="ms-rubric">{inner}</div>'
        if head_type == "dateline":
            return f'<div class="ms-dateline">{inner}</div>'
        return f'<div class="ms-head">{inner}</div>'

    # ── CHANGE 2: new _render_trailer method ───────────────────────────────
    def _render_trailer(self, trailer_el: ET.Element) -> str:
        # lb_as_br=True so manuscript line structure is visible in the explicit
        inner = "".join(self._render_children(trailer_el, "", "", lb_as_br=True))
        return (
            '<div class="ms-trailer font-serif-geo text-center mt-8 pt-4 '
            'border-t border-gray-200 text-sm italic text-gray-500">'
            f'{inner}</div>'
        )

    def _render_paragraph(self, p_el: ET.Element) -> str:
        par_id = _xml_id_attr(p_el) or f"p{id(p_el)}"
        par_n  = p_el.get("n", par_id.lstrip("p"))
        parts  = [
            f'<span class="par-num" title="¶{par_n}">¶{par_n}</span>',
        ]
        parts.extend(self._render_children(p_el, par_id, par_n))
        inner = "".join(parts)
        return f'<p id="{par_id}">{inner}</p>'

    def _render_children(self, el: ET.Element, par_id: str, par_n: str,
                          lb_as_br: bool = False) -> list:
        """Recursively render children of an element to HTML strings.

        lb_as_br: when True, <lb> elements emit <br> instead of being dropped.
                  Pass True for head and trailer contexts; leave False (default)
                  for paragraph body so text reflows as prose.
        """
        parts = []

        # Text before first child
        if el.text:
            parts.append(html_lib.escape(el.text))

        for child in el:
            tag = child.tag.replace("{http://www.tei-c.org/ns/1.0}", "")

            if tag == "pb":
                parts.append(self._render_pb(child))

            elif tag == "app":
                parts.append(self._render_app(child, par_id, par_n))

            elif tag == "note":
                n_id = _xml_id_attr(child) or f"note-{id(child)}"
                note_text = html_lib.escape("".join(child.itertext()))
                num = child.get("n", "*")
                parts.append(
                    f'<span class="note-anchor" title="{note_text}" id="anchor-{n_id}">{num}</span>'
                )

            elif tag == "hi":
                rend  = child.get("rend", "")
                # ── propagate lb_as_br into nested hi elements ──────────────
                inner = "".join(self._render_children(child, par_id, par_n, lb_as_br))
                if rend == "initial":
                    parts.append(
                        f'<span class="geo-initial" style="color:var(--crimson);'
                        f'font-family:\'Noto Sans Georgian\',sans-serif;'
                        f'font-weight:500;">{inner}</span>'
                    )
                elif rend == "rubric":
                    parts.append(
                        f'<span class="geo-rubric" style="color:var(--crimson);">{inner}</span>'
                    )
                else:
                    parts.append(f'<em>{inner}</em>')

            elif tag == "lb":
                # ── CHANGE 3: emit <br> in head/trailer; drop in paragraphs ─
                if lb_as_br:
                    parts.append("<br>")
                # else: pass — reflow in CSS

            elif tag == "w":
                lemma_ref = child.get("lemma", "")
                lex_id = lemma_ref.lstrip("#")
                word = html_lib.escape("".join(child.itertext()))
                if lex_id:
                    parts.append(f'<span class="lex-word" data-lemma="{html_lib.escape(lex_id)}">{word}</span>')
                else:
                    parts.append(word)

            elif tag == "quote":
                source = child.get("source", "").lstrip("#")
                # ── propagate lb_as_br into quotes ──────────────────────────
                inner = "".join(self._render_children(child, par_id, par_n, lb_as_br))
                source_attr = f' data-source="{html_lib.escape(source)}"' if source else ""
                parts.append(f'<span class="geo-quote"{source_attr}>{inner}</span>')

            else:
                # ── propagate lb_as_br into any other inline element ────────
                inner = "".join(self._render_children(child, par_id, par_n, lb_as_br))
                parts.append(inner)

            if child.tail:
                parts.append(html_lib.escape(child.tail))

        return parts

    # ── Page break rendering ───────────────────────────

    def _render_pb(self, pb_el: ET.Element) -> str:
        """
        Render a <pb> element as a .folio-milestone span.
        If the facs map has an entry for this folio, emit data-facs and data-sp.
        Also stores the first folio facs for viewer initialisation.
        """
        n   = pb_el.get("n", "")
        wit = pb_el.get("wit", "").lstrip("#")

        # @facs on the element itself (from TEI) takes precedence over map
        facs_from_attr = pb_el.get("facs", "")

        facs_entry = self._facs_map.get(n, {})
        facs_url   = facs_from_attr or facs_entry.get("facs", "")
        sp         = facs_entry.get("sp", 0)

        # Record the first facs-bearing folio for viewer init
        if facs_url and not self._first_facs:
            self._first_facs  = facs_url
            self._first_folio = n
            self._first_sp    = sp

        # Build data attributes
        data_attrs = f'data-wit="{html_lib.escape(wit)}" data-folio="{html_lib.escape(n)}"'
        if facs_url:
            data_attrs += f' data-facs="{html_lib.escape(facs_url)}"'
        if sp:
            data_attrs += f' data-sp="{sp}"'

        title = f"Sin. geo. {wit}, f. {n}"

        return (
            f'<span class="folio-milestone" {data_attrs} title="{title}">{n}</span>'
        )

    # ── Apparatus ─────────────────────────────────────

    def _render_app(self, app_el: ET.Element, par_id: str, par_n: str) -> str:
        """
        Render a TEI <app> element:
          - Extract <lem> text → inline span linked to apparatus entry
          - Build AppEntry from <rdg> elements
          Returns inline HTML string.
        """
        self._app_counter += 1
        app_n  = self._app_counter
        app_id = f"app-{app_n}"

        lem_el   = app_el.find("tei:lem", NS)
        lem_text = html_lib.escape("".join(lem_el.itertext())) if lem_el is not None else ""
        lem_wit  = _attr(lem_el, "wit", "").lstrip("#") if lem_el is not None else ""

        readings: List[RdgData] = []
        dominant_type = "orthographic"
        for rdg_el in app_el.findall("tei:rdg", NS):
            rdg_text = "".join(rdg_el.itertext())
            rdg_wit  = _attr(rdg_el, "wit", "").lstrip("#")
            rdg_type = _attr(rdg_el, "type", "orthographic")
            type_class, type_label = self.RDG_TYPES.get(rdg_type, ("rdg-orth", rdg_type))
            readings.append(RdgData(
                text=rdg_text, witness=rdg_wit,
                type_raw=rdg_type, type_class=type_class, type_label=type_label,
            ))
            dominant_type = rdg_type

        entry = AppEntry(
            n=app_n, par_id=par_id, par_n=par_n,
            lemma=lem_text.replace("&amp;", "&"),
            type=dominant_type, readings=readings,
        )
        self._apparatus.append(entry)

        return (
            f'<span class="app-inline" data-app="{app_id}" '
            f'title="ვარ. {app_n}">{lem_text}</span>'
        )


# ── Attestation collector ──────────────────────────────

def _get_context(para_el: ET.Element, target_w: ET.Element):
    """
    Walk para_el mixed content in document order, accumulating text.
    Returns (full_text, word_start, word_len) for target_w's text.
    """
    buf = []
    start = [None]
    end_p = [None]

    def walk(el):
        if el.text:
            if el is target_w:
                start[0] = sum(len(s) for s in buf)
            buf.append(el.text)
            if el is target_w:
                end_p[0] = sum(len(s) for s in buf)
        for child in el:
            walk(child)
            if child.tail:
                buf.append(child.tail)

    walk(para_el)
    full = "".join(buf)
    s = start[0] if start[0] is not None else 0
    e = end_p[0] if end_p[0] is not None else s
    return full, s, e - s


def collect_attestations(xml_path: Path, text_id: str, title: str) -> dict:
    """
    Scan xml_path for <w lemma="#lex-{id}"> annotations.
    Returns {lex_id: [{text_id, title, para_id, para_n, quote}]}.
    One entry per unique (lex_id, text_id, para_id) — deduplicates repeated
    occurrences of the same word within the same paragraph.
    quote is ~80 chars of parent-paragraph text centred on the word,
    with normalised whitespace.
    """
    _P_TAGS = {f"{{{_TEI}}}p", f"{{{_TEI}}}ab"}

    tree = ET.parse(xml_path)
    root = tree.getroot()

    # Build child→parent map for upward traversal
    parent_map: dict = {}
    for parent in root.iter():
        for child in parent:
            parent_map[child] = parent

    result: dict = {}
    seen: set = set()   # (lex_id, text_id, para_id)

    for w_el in root.findall(f".//{{{_TEI}}}w"):
        lemma_ref = w_el.get("lemma", "")
        if not lemma_ref.startswith("#"):
            continue
        lex_id = lemma_ref[1:]

        # Walk up to nearest <p> or <ab>
        para_el = None
        node = w_el
        while node in parent_map:
            node = parent_map[node]
            if node.tag in _P_TAGS:
                para_el = node
                break

        if para_el is None:
            continue

        para_id = para_el.get(f"{{{_XML}}}id", "")
        para_n  = para_el.get("n", para_id.lstrip("p") if para_id else "")

        key = (lex_id, text_id, para_id)
        if key in seen:
            continue
        seen.add(key)

        full_text, wstart, wlen = _get_context(para_el, w_el)
        HALF = 40
        cs = max(0, wstart - HALF)
        ce = min(len(full_text), wstart + wlen + HALF)
        raw = full_text[cs:ce]
        quote = " ".join(raw.split())   # normalise whitespace
        if cs > 0:
            quote = "…" + quote
        if ce < len(full_text):
            quote += "…"

        result.setdefault(lex_id, []).append({
            "text_id": text_id,
            "title":   title,
            "para_id": para_id,
            "para_n":  para_n,
            "quote":   quote,
        })

    return result